package dark.comecloser;

import java.io.File;
import java.util.Arrays;

import net.minecraftforge.common.config.Configuration;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.FMLEventChannel;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.relauncher.Side;

@Mod(modid = ComeCloser.MOD_ID, name = ComeCloser.MOD_NAME, version = ComeCloser.VERSION, useMetadata = true)
public class ComeCloser
{
    /*Idea cache a list of boolean values in the player to control if the tag should be rendered fully or not
     *As well cache range values per player on the server and detect and send player data to client when players are in range
     *Use this as well to control render ranges per player server side doing ray traces to determine ranges
     *
     */
    // @Mod Prerequisites
    public static final String MAJOR_VERSION = "@MAJOR@";
    public static final String MINOR_VERSION = "@MINOR@";
    public static final String REVIS_VERSION = "@REVIS@";
    public static final String BUILD_VERSION = "@BUILD@";

    // @Mod
    public static final String MOD_ID = "ComeCloser";
    public static final String MOD_NAME = "Come Closer";
    public static final String VERSION = MAJOR_VERSION + "." + MINOR_VERSION + "." + REVIS_VERSION + "." + BUILD_VERSION;

    public static final String CHANNEL = ComeCloser.MOD_ID;

    @Instance(ComeCloser.MOD_ID)
    public static ComeCloser Instance;

    @Metadata(ComeCloser.MOD_ID)
    public static ModMetadata meta;

    @SidedProxy(clientSide = "dark.comecloser.ClientProxy", serverSide = "dark.comecloser.CommonProxy")
    public static CommonProxy proxy;

    static FMLEventChannel packetHandler;

    public static float standingRange = 64f;
    public static float sneakRange = 32f;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        packetHandler = NetworkRegistry.INSTANCE.newEventDrivenChannel(CHANNEL);
        packetHandler.register(proxy);
        // // Config ////
        if (event.getSide() == Side.SERVER)
        {
            Configuration config = new Configuration(new File(cpw.mods.fml.common.Loader.instance().getConfigDir(), "ComeCloser.cfg"));
            config.load();
            sneakRange = config.get(Configuration.CATEGORY_GENERAL, "SneakRange", 32).getInt();
            standingRange = config.get(Configuration.CATEGORY_GENERAL, "NormalRange", 64).getInt();
            config.save();
        }
        this.loadModMeta();
        FMLCommonHandler.instance().bus().register(proxy);

    }

    public void loadModMeta()
    {
        meta.modId = ComeCloser.MOD_ID;
        meta.name = ComeCloser.MOD_NAME;
        meta.description = "Help improve SMP play by changing how the player's name tag renders. Allows the range to be managed by the server so that name tags do not render at 64 blocks away";

        meta.url = "www.BuildBroken.com";

        meta.logoFile = "/cc_logo.png";
        meta.version = ComeCloser.VERSION;
        meta.authorList = Arrays.asList("DarkGuardsman aka DarkCow");
        meta.credits = "Fans - without fans this mod would have died a long time ago";
        meta.autogenerated = false;

    }

}