package com.builtbroken.comecloser;

import com.builtbroken.comecloser.network.SyncSettings;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.util.Arrays;

@Mod(modid = ComeCloser.MOD_ID, name = ComeCloser.MOD_NAME, version = ComeCloser.VERSION, useMetadata = true)
public class ComeCloser
{
    // @Mod Prerequisites
    public static final String MC_VERSION = "@MC@";
    public static final String MAJOR_VERSION = "@MAJOR@";
    public static final String MINOR_VERSION = "@MINOR@";
    public static final String REVIS_VERSION = "@REVIS@";
    public static final String BUILD_VERSION = "@BUILD@";

    // @Mod
    public static final String MOD_ID = "comecloser";
    public static final String MOD_NAME = "Come Closer";
    public static final String VERSION = MC_VERSION + "." + MAJOR_VERSION + "." + MINOR_VERSION + "." + REVIS_VERSION + "." + BUILD_VERSION;

    @Mod.Instance(ComeCloser.MOD_ID)
    public static ComeCloser instance;

    @Mod.Metadata(ComeCloser.MOD_ID)
    public static ModMetadata meta;

    @SidedProxy(clientSide = "com.builtbroken.comecloser.ClientProxy", serverSide = "com.builtbroken.comecloser.CommonProxy")
    public static CommonProxy proxy;

    public static Logger LOGGER;

    public static SimpleNetworkWrapper network;

    /** Tag distance standing */
    public static float standingRange = 64f;
    /** Tag distance sneaking */
    public static float sneakRange = 32f;
    /** Do ray trace for tag rendering */
    public static boolean doRayTrace = true;
    /** Do chat messages when syncing chat messages */
    public static boolean doChatMessages = true;

    protected void setDefaults()
    {
        ComeCloser.sneakRange = 32;
        ComeCloser.standingRange = 64;
        ComeCloser.doRayTrace = true;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        int packetDiscriminator = 4;
        LOGGER = LogManager.getLogger(MOD_ID);
        // // Config ////
        if (event.getSide() == Side.SERVER)
        {
            Configuration config = new Configuration(new File(event.getModConfigurationDirectory(), "ComeCloser.cfg"));
            config.load();
            sneakRange = config.getInt("SneakRange", Configuration.CATEGORY_GENERAL, 32, 0, 300, "Distance in meters (blocks) to render name tag while sneaking");
            standingRange = config.getInt("NormalRange", Configuration.CATEGORY_GENERAL, 64, 0, 300, "Distance in meters (blocks) to render name tag");
            doRayTrace = config.getBoolean("DoLineOfSight", Configuration.CATEGORY_GENERAL, doRayTrace, "Enabled line of sight check before rendering name tags to allow players to hide behind walls. " +
                    "(line of sight -> ray trace from player to player eye line)");
            doChatMessages = config.getBoolean("DoChatMessages", Configuration.CATEGORY_GENERAL, doChatMessages, "Disables chat messages for syncing settings between server and client");

            config.save();
        }
        this.loadModMeta();
        MinecraftForge.EVENT_BUS.register(proxy);
        network = NetworkRegistry.INSTANCE.newSimpleChannel("ComeCloserChannel");
        network.registerMessage(SyncSettings.Handler.class, SyncSettings.class, packetDiscriminator++, Side.CLIENT);
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {}

    public void loadModMeta()
    {
        meta.modId = ComeCloser.MOD_ID;
        meta.name = ComeCloser.MOD_NAME;
        meta.description = "Allows control over name tag rendering to improve PvP gameplay.";
        meta.url = "http://www.builtbroken.com";
        meta.logoFile = "/cc_logo.png";
        meta.version = ComeCloser.VERSION;
        meta.authorList = Arrays.asList("DarkGuardsman", "Hennamann");
        meta.credits = "Fans - without fans this mod would have died a long time ago";
        meta.autogenerated = false;
    }
}