package com.builtbroken.comecloser;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.FMLEventChannel;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.relauncher.Side;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;

import java.io.File;
import java.util.Arrays;

@Mod(modid = ComeCloser.MOD_ID, name = ComeCloser.MOD_NAME, version = ComeCloser.VERSION, useMetadata = true)
public class ComeCloser
{
    // @Mod Prerequisites
    public static final String MAJOR_VERSION = "@MAJOR@";
    public static final String MINOR_VERSION = "@MINOR@";
    public static final String REVIS_VERSION = "@REVIS@";
    public static final String BUILD_VERSION = "@BUILD@";

    // @Mod
    public static final String MOD_ID = "ComeCloser";
    public static final String MOD_NAME = "Come Closer";
    public static final String VERSION = MAJOR_VERSION + "." + MINOR_VERSION + "." + REVIS_VERSION + "." + BUILD_VERSION;

    public static final String CHANNEL = ComeCloser.MOD_ID;

    @Instance(ComeCloser.MOD_ID)
    public static ComeCloser Instance;

    @Metadata(ComeCloser.MOD_ID)
    public static ModMetadata meta;

    @SidedProxy(clientSide = "com.builtbroken.comecloser.ClientProxy", serverSide = "com.builtbroken.comecloser.CommonProxy")
    public static CommonProxy proxy;

    static FMLEventChannel packetHandler;

    /** Tag distance standing */
    public static float standingRange = 64f;
    /** Tag distance sneaking */
    public static float sneakRange = 32f;
    /** Do ray trace for tag rendering */
    public static boolean doRayTrace = true;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        packetHandler = NetworkRegistry.INSTANCE.newEventDrivenChannel(CHANNEL);
        packetHandler.register(proxy);
        // // Config ////
        if (event.getSide() == Side.SERVER)
        {
            Configuration config = new Configuration(new File(event.getModConfigurationDirectory(), "ComeCloser.cfg"));
            config.load();
            sneakRange = config.getInt("SneakRange", Configuration.CATEGORY_GENERAL, 32, 0, 300, "Distance in meters (blocks) to render name tag while sneaking");
            standingRange = config.getInt("NormalRange", Configuration.CATEGORY_GENERAL, 64, 0, 300, "Distance in meters (blocks) to render name tag");
            config.save();
        }
        this.loadModMeta();
        FMLCommonHandler.instance().bus().register(proxy);
        MinecraftForge.EVENT_BUS.register(proxy);
    }

    public void loadModMeta()
    {
        meta.modId = ComeCloser.MOD_ID;
        meta.name = ComeCloser.MOD_NAME;
        meta.description = "Help improve PvP by changing how the player's name tag renders. " +
                "Allows the range to be managed by the server so that name tags do not render at 64 blocks away";

        meta.url = "www.BuildBroken.com";

        meta.logoFile = "/cc_logo.png";
        meta.version = ComeCloser.VERSION;
        meta.authorList = Arrays.asList("DarkGuardsman aka DarkCow");
        meta.credits = "Fans - without fans this mod would have died a long time ago";
        meta.autogenerated = false;
    }
}